name: futurama_wiki
description: Futurama wiki application as a test project for the interview
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: 6.1.0
  chopper: 6.1.1
  dart_code_metrics: 5.7.2
  flutter_bloc: 8.1.2
  get_it: 7.2.0
  intl: 0.18.0
  json_annotation: 4.8.0
  url_launcher: 6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^6.1.0
  build_runner: 2.3.3
  cached_network_image: 3.2.3
  chopper_generator: 6.0.0
  flutter_gen_runner: 5.2.0
  flutter_lints: 2.0.1
  intl_utils: 2.8.2
  json_serializable: 6.6.1



flutter:

  uses-material-design: true

